---
title: "Class R6 for the referential"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
library(readxl)
library(dplyr)
library(purrr)

```

# r6_referential

With XlsForm, we can not filter as we want because the order inside the file is important. For me the first thing to do is to separate our file with begin and end group

```{r function-r6_referential}
#' Referential class is a class to load, check and manipulate the XLSForm 
#' @importFrom R6 R6Class
#' 
#' @export

Referential <- R6::R6Class(classname = "Referential",
                           public = list(
                             #' @description 
                             #' read the xlsx for each sheet and return a named list
                             #' @param path path to the xlsForm
                             #' 
                             #' @importFrom readxl excel_sheets read_xlsx
                             #' 
                             #' @return named list
                             initialize = function(path){
                               # Define path
                               self$path <- path
                               
                               # Get sheets of xlsx
                               sheets <- names_of_sheet(path)
                               
                               # Read the xlsx file 
                               data <- lapply(
                                 sheets, 
                                 function(x){
                                   read_xlsx(path = path, sheet = x)}) |>
                                      setNames(nm = sheets)
                               # TODO checking survey and other sheets
                               
                               # survey have to be a xlsform
                               if(!contains_group(data$survey)){
                                 stop("the sheet 'survey' dosen't groups - i.e. questions organised as module")
                               }
                               
                               self$data <- data
                               
                               # Get groups 
                               
                               self$get_groups()
                             },
                             #' @field data named list for the xlsx file
                             data = list(),
                             #' @field by_groups survey data separate by begin and end to manipulate data
                             by_groups = list(),
                             #' @field path path for the xlsx file
                             path  = character(0),
                             #' @description get data by groups of begin and end
                             get_groups = function(){
                               self$by_groups <- get_groups(self$data$survey)
                               
                               message("result is store in `by_groups` sub-element")
                             }
                           ),
                           private = list(
                             
                           )
)
```

```{r development-test}
ref <- Referential$new(
  path = system.file("SurveyDesigner_Referential.xlsx", package = "surveyDesigner") 
)
```


```{r examples-r6_referential}
ref <- Referential$new(
  path = system.file("SurveyDesigner_Referential.xlsx", package = "surveyDesigner") 
)

head(ref$data$survey)

# Example by groups
ref$by_groups$group_intro
```

```{r tests-r6_referential}
test_that("r6_referential works", {
  ref <- Referential$new(
    path = system.file("SurveyDesigner_Referential.xlsx", package = "surveyDesigner") 
  )
  
  expect_true( inherits(ref, "R6") )
  
  expect_error(
    Referential$new(
      path = "not_good_sheet.xlsx" 
    )
  )
  
  expect_error(
    Referential$new(
      path = "wt_xlsform_in_survey.xlsx" 
    )
  )

})
```


# Utils for xlsx
    

```{r function-utils_xlsform}
survey_designer <- new.env()

assign(
  "names_sheets", 
  c("referential_type",
    "survey",
    "choices",
    "indicator",
    "indicator_survey",
    "indicator_choices", 
    "indicator_population",
    "indicator_disaggregation"
  ), 
  envir = survey_designer)


#' Get groups form begin and end into a list with data and information
#' 
#' @param data data form the survey sheet
#'
#' @importFrom purrr map2 set_names map
#' @importFrom dplyr slice filter
#' 
#' @return list
#' 
get_groups <- function(data){
  # only on survey

begin_start <- grep(x = data[["type"]], "begin_")
end_stop <- grep(x = data[["type"]], "end_")



if(length(begin_start) != length(end_stop)){
  stop("Miss one begin or stop in the data")
}

if(!all(begin_start < end_stop)){
  stop("One begin is before a end")
}

by_begin_end <- map2(begin_start, end_stop,
                            function(x,y){
                              
                              data_to_get <- data %>% 
                                slice(x:y)
                              by_groups <- list(data = data_to_get %>%
                                                  filter(!type %in% c("begin_group", "end_group")),
                                                information = data_to_get %>%
                                                  filter(type %in% c("begin_group", "end_group"))
                              )
                              # names(by_groups) <- by_groups[["information"]][["name"]]
                              
                              by_groups
                            }) %>% 
  purrr::set_names(nm = purrr::map(., ~ .x[["information"]][["name"]][1]))

 return(by_begin_end)
}

#' Get choices for one question
#'
#' @param data data of choices
#' @param indicator the name of the indicator for the question
#' @param lg language to use
#'
#' @importFrom dplyr filter select contains
#'
#' @return a data.frame to join
get_choices_for_question <- function(data, indicator, lg){
  data %>% 
    filter(list_name == indicator) %>% 
    select(list_name, name, contains(lg))
}

#' function to find if we manipulate a xlsform
#'
#' @param data data of the survey
#'
#' @noRd

contains_group <- function(data){
  any(grepl(x = data[["type"]], pattern = 'begin_group|begin_repeat|end_group|end_repeat'))
}

#' function to check name of sheets
#'
#' @param path path to the xlsform
#'
#' @noRd
names_of_sheet <- function(path){
  sheets <- excel_sheets(path)
  if(all(sheets == get("names_sheets", envir = survey_designer))){
    return(sheets)
  }else{
    stop("Problem with the name of sheets")
  }
}
```
 
 
```{r development-utils, eval = FALSE}

data <- ref$data$survey

begin_start <- grep(x = , "begin_")
end_stop <- grep(x = data[["type"]], "end_")



if(length(begin_start) != length(end_stop)){
  stop("Miss one begin or stop in the data")
}

if(!all(begin_start < end_stop)){
  stop("One begin is before a end")
}

by_begin_end <- purrr::map2(begin_start, end_stop,
                            function(x,y){
                              
                              data_to_get <- data %>% 
                                slice(x:y)
                              by_groups <- list(data = data_to_get %>%
                                                  filter(!type %in% c("begin_group", "end_group")),
                                                information = data_to_get %>%
                                                  filter(type %in% c("begin_group", "end_group"))
                              )
                              # names(by_groups) <- by_groups[["information"]][["name"]]
                              
                              by_groups
                            }) %>% 
  purrr::set_names(nm = purrr::map(., ~ .x[["information"]][["name"]][1]))


```

  
  
```{r tests-utils_xlsform}
test_that("utils_xlsform works", {
  expect_true(inherits(get_groups, "function")) 
  
ref <- Referential$new(
  path = system.file("SurveyDesigner_Referential.xlsx", package = "surveyDesigner") 
)

result <- get_groups(ref$data$survey)

expect_named(result[[1]], c("data", "information"))
expect_type(result, "list")


expect_true(inherits(get_choices_for_question, "function"))
get_chocies <- get_choices_for_question(ref$data$choices, "pop_groups", "English")

expect_type(get_chocies, "list")

})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_r6_referential.Rmd", 
  vignette_name = "Class R6 for the referential"
  )
```

