# WARNING - Generated by {fusen} from /dev/flat_r6_referential.Rmd: do not edit by hand

test_that("r6_referential works", {
  ref <- Referential$new(
    path = system.file("household_survey_americas.xlsx", package = "surveyDesigner") 
  )
  
  expect_true( inherits(ref, "R6") )
  
  expect_error(
    Referential$new(
      path = "not_good_sheet.xlsx" 
    )
  )
  
  expect_error(
    Referential$new(
      path = "wt_xlsform_in_survey.xlsx" 
    )
  )

})
