# WARNING - Generated by {fusen} from /dev/flat_r6_referential.Rmd: do not edit by hand

test_that("utils_xlsform works", {
  expect_true(inherits(get_groups, "function")) 
  
ref <- Referential$new(
  path = system.file("household_survey_americas.xlsx", package = "surveyDesigner") 
)

result <- get_groups(ref$data$survey)

expect_named(result[[1]], c("data", "information"))
expect_type(result, "list")


expect_true(inherits(get_choices_for_question, "function"))
get_chocies <- get_choices_for_question(ref$data$choices, "pop_groups", "English")

expect_type(get_chocies, "list")

})
