# WARNING - Generated by {fusen} from /dev/flat_r6_referential.Rmd: do not edit by hand

test_that("utils_indicator_map works", {
  expect_true(inherits(has_variables_for_indicators, "function"))
  
  expect_true(inherits(indicator_linked_population, "function"))
  
  expect_true(inherits(population_linked_indicator, "function"))
  
  expect_true(inherits(indicator_linked_variable, "function"))
})
