# WARNING - Generated by {fusen} from /dev/flat_r6_referential.Rmd: do not edit by hand

#' function to check that if an indicator is defined it should map with at
#'   least one variable from the survey worksheet
#'
#' @param path path to the xlsform
#' 
#' @importFrom readxl excel_sheets
#'
#' @noRd
has_variables_for_indicators <- function(path){
           
  # if(all(indicator_disaggregation  %in% get("names_indicator_disaggregation", envir = survey_designer)) ){
  #   return(indicator_disaggregation)
  # } else {
  #   stop("Problem with the name of sheet for indicator_disaggregation")
  # }
}

#' function to check that an indicator should map with at least one population
#'
#' @param path path to the xlsform
#' 
#' @importFrom readxl excel_sheets
#'
#' @noRd
indicator_linked_population <- function(path){
           
  # if(all(indicator_disaggregation  %in% get("names_indicator_disaggregation", envir = survey_designer)) ){
  #   return(indicator_disaggregation)
  # } else {
  #   stop("Problem with the name of sheet for indicator_disaggregation")
  # }
}

#' function to check that if a relation between one population and one indicator
#'  is recorded, the indicator should also be defined in the indicator frame
#'
#' @param path path to the xlsform
#' 
#' @importFrom readxl excel_sheets
#'
#' @noRd
population_linked_indicator <- function(path){
           
  # if(all(indicator_disaggregation  %in% get("names_indicator_disaggregation", envir = survey_designer)) ){
  #   return(indicator_disaggregation)
  # } else {
  #   stop("Problem with the name of sheet for indicator_disaggregation")
  # }
}

#' function to check that if an indicator is defined to map with variables 
#' from the survey worksheet, then all those variables should actually be 
#' present in the survey frame
#'
#' @param path path to the xlsform
#' 
#' @importFrom readxl excel_sheets
#'
#' @noRd
indicator_linked_variable <- function(path){
           
  # if(all(indicator_disaggregation  %in% get("names_indicator_disaggregation", envir = survey_designer)) ){
  #   return(indicator_disaggregation)
  # } else {
  #   stop("Problem with the name of sheet for indicator_disaggregation")
  # }
}
 

